cmake_minimum_required(VERSION 3.26)
project(tinycl VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)

add_executable(tinycl ${CMAKE_CURRENT_SOURCE_DIR}/tinycl/Main.cpp)
target_link_libraries(tinycl PRIVATE uring)
